import { IBox } from "../models/StoreModels"

export interface IBoxArr extends Array<IBox> {}

export const boxData: IBoxArr = [
    {
        BoxIdBarCode: 323617,
        Location: "L7957050050",
        DepId: 5555,
        DepartmentName: "Department of Aerophysics",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 485072,
        Location: "5556",
        DepId: 5556,
        DepartmentName: "Department of Science",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 81552,
        Location: "legal",
        DepId: 5557,
        DepartmentName: "Department of Agriculture",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 739922,
        Location: "L3971521886",
        DepId: 5558,
        DepartmentName: "Department of Chemistry",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 970173,
        Location: "L6164995787",
        DepId: 5559,
        DepartmentName: "Department of Business",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 62536,
        Location: "L2338653742",
        DepId: 5560,
        DepartmentName: "Department of Social Studies",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 520868,
        Location: "L9186517090",
        DepId: 5555,
        DepartmentName: "Department of Aerophysics",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 978267,
        Location: "L4551179809",
        DepId: 5556,
        DepartmentName: "Department of Science",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 740127,
        Location: "L8320275040",
        DepId: 5557,
        DepartmentName: "Department of Agriculture",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 909880,
        Location: "L0484444220",
        DepId: 5558,
        DepartmentName: "Department of Chemistry",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 946158,
        Location: "L1840134305",
        DepId: 5559,
        DepartmentName: "Department of Business",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 749515,
        Location: "L2352083885",
        DepId: 5560,
        DepartmentName: "Department of Social Studies",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 879407,
        Location: "L8508749600",
        DepId: 5555,
        DepartmentName: "Department of Aerophysics",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 821065,
        Location: "L7114956371",
        DepId: 5556,
        DepartmentName: "Department of Science",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 8644,
        Location: "L6920993074",
        DepId: 5557,
        DepartmentName: "Department of Agriculture",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 482870,
        Location: "L5425950578",
        DepId: 5558,
        DepartmentName: "Department of Chemistry",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 882980,
        Location: "L4695700298",
        DepId: 5559,
        DepartmentName: "Department of Business",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 487313,
        Location: "L9411646433",
        DepId: 5560,
        DepartmentName: "Department of Social Studies",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 677058,
        Location: "L0220868042",
        DepId: 5555,
        DepartmentName: "Department of Aerophysics",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 739441,
        Location: "L1329487621",
        DepId: 5556,
        DepartmentName: "Department of Science",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 36641,
        Location: "L8421437127",
        DepId: 5557,
        DepartmentName: "Department of Agriculture",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 692492,
        Location: "L8911901687",
        DepId: 5558,
        DepartmentName: "Department of Chemistry",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 108299,
        Location: "L6792267775",
        DepId: 5559,
        DepartmentName: "Department of Business",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 299680,
        Location: "L5857183014",
        DepId: 5560,
        DepartmentName: "Department of Social Studies",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 428508,
        Location: "L7879253556",
        DepId: 5555,
        DepartmentName: "Department of Aerophysics",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 248182,
        Location: "L5326679639",
        DepId: 5556,
        DepartmentName: "Department of Science",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 639433,
        Location: "L6818600468",
        DepId: 5557,
        DepartmentName: "Department of Agriculture",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 134892,
        Location: "L4292596905",
        DepId: 5558,
        DepartmentName: "Department of Chemistry",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 233369,
        Location: "L0664729525",
        DepId: 5559,
        DepartmentName: "Department of Business",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 322828,
        Location: "L7745464935",
        DepId: 5560,
        DepartmentName: "Department of Social Studies",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 188473,
        Location: "L3346974642",
        DepId: 5555,
        DepartmentName: "Department of Aerophysics",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 778756,
        Location: "L9180049737",
        DepId: 5556,
        DepartmentName: "Department of Science",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 414234,
        Location: "L8033470488",
        DepId: 5557,
        DepartmentName: "Department of Agriculture",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 112578,
        Location: "L3094985211",
        DepId: 5558,
        DepartmentName: "Department of Chemistry",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 243813,
        Location: "L7668245898",
        DepId: 5559,
        DepartmentName: "Department of Business",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 668549,
        Location: "L9695278353",
        DepId: 5560,
        DepartmentName: "Department of Social Studies",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 590200,
        Location: "L3447552972",
        DepId: 5555,
        DepartmentName: "Department of Aerophysics",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 559530,
        Location: "L7068285740",
        DepId: 5556,
        DepartmentName: "Department of Science",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 410344,
        Location: "L2346291773",
        DepId: 5557,
        DepartmentName: "Department of Agriculture",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 993620,
        Location: "L7853428685",
        DepId: 5558,
        DepartmentName: "Department of Chemistry",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 973179,
        Location: "L2115963105",
        DepId: 5559,
        DepartmentName: "Department of Business",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 8508,
        Location: "L1422972364",
        DepId: 5560,
        DepartmentName: "Department of Social Studies",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 399414,
        Location: "L9546484113",
        DepId: 5555,
        DepartmentName: "Department of Aerophysics",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 44031,
        Location: "L6579311177",
        DepId: 5556,
        DepartmentName: "Department of Science",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 170988,
        Location: "L0897439376",
        DepId: 5557,
        DepartmentName: "Department of Agriculture",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 636538,
        Location: "L2323589156",
        DepId: 5558,
        DepartmentName: "Department of Chemistry",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 466286,
        Location: "L6006381842",
        DepId: 5559,
        DepartmentName: "Department of Business",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 666693,
        Location: "L4467214925",
        DepId: 5560,
        DepartmentName: "Department of Social Studies",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 26898,
        Location: "L7259627492",
        DepId: 5555,
        DepartmentName: "Department of Aerophysics",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 838811,
        Location: "L3034865465",
        DepId: 5556,
        DepartmentName: "Department of Science",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 268623,
        Location: "L9187117630",
        DepId: 5557,
        DepartmentName: "Department of Agriculture",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 647543,
        Location: "L8752060365",
        DepId: 5558,
        DepartmentName: "Department of Chemistry",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 431949,
        Location: "L7720588827",
        DepId: 5559,
        DepartmentName: "Department of Business",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 345299,
        Location: "L7347885698",
        DepId: 5560,
        DepartmentName: "Department of Social Studies",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 376131,
        Location: "L4030706959",
        DepId: 5555,
        DepartmentName: "Department of Aerophysics",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 112513,
        Location: "L0411746898",
        DepId: 5556,
        DepartmentName: "Department of Science",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 268822,
        Location: "L7170579545",
        DepId: 5557,
        DepartmentName: "Department of Agriculture",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 414147,
        Location: "L7227122727",
        DepId: 5558,
        DepartmentName: "Department of Chemistry",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 151645,
        Location: "L1079588965",
        DepId: 5559,
        DepartmentName: "Department of Business",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 450502,
        Location: "L9338792560",
        DepId: 5560,
        DepartmentName: "Department of Social Studies",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 604250,
        Location: "L1286052564",
        DepId: 5555,
        DepartmentName: "Department of Aerophysics",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 517630,
        Location: "L6339333656",
        DepId: 5556,
        DepartmentName: "Department of Science",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 689905,
        Location: "L9354077536",
        DepId: 5557,
        DepartmentName: "Department of Agriculture",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 37033,
        Location: "L1737986698",
        DepId: 5558,
        DepartmentName: "Department of Chemistry",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 214564,
        Location: "L3863202090",
        DepId: 5559,
        DepartmentName: "Department of Business",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 174919,
        Location: "L8538525824",
        DepId: 5560,
        DepartmentName: "Department of Social Studies",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 276617,
        Location: "L9123045906",
        DepId: 5555,
        DepartmentName: "Department of Aerophysics",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 316754,
        Location: "L6688907887",
        DepId: 5556,
        DepartmentName: "Department of Science",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 479254,
        Location: "L8110805787",
        DepId: 5557,
        DepartmentName: "Department of Agriculture",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 137813,
        Location: "L5319819978",
        DepId: 5558,
        DepartmentName: "Department of Chemistry",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 708658,
        Location: "L4657589342",
        DepId: 5559,
        DepartmentName: "Department of Business",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 746531,
        Location: "L6571682834",
        DepId: 5560,
        DepartmentName: "Department of Social Studies",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 798485,
        Location: "L0802286097",
        DepId: 5555,
        DepartmentName: "Department of Aerophysics",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 939125,
        Location: "L5335969733",
        DepId: 5556,
        DepartmentName: "Department of Science",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 780435,
        Location: "L8216711204",
        DepId: 5557,
        DepartmentName: "Department of Agriculture",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 739374,
        Location: "L2296853544",
        DepId: 5558,
        DepartmentName: "Department of Chemistry",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 414098,
        Location: "L1500727296",
        DepId: 5559,
        DepartmentName: "Department of Business",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 688247,
        Location: "L8609941019",
        DepId: 5560,
        DepartmentName: "Department of Social Studies",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 765823,
        Location: "L2098081502",
        DepId: 5555,
        DepartmentName: "Department of Aerophysics",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 938294,
        Location: "L8494695274",
        DepId: 5556,
        DepartmentName: "Department of Science",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 962761,
        Location: "L2827959127",
        DepId: 5557,
        DepartmentName: "Department of Agriculture",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 793388,
        Location: "L1046151290",
        DepId: 5558,
        DepartmentName: "Department of Chemistry",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 342550,
        Location: "L7653928269",
        DepId: 5559,
        DepartmentName: "Department of Business",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 966697,
        Location: "L4826663099",
        DepId: 5560,
        DepartmentName: "Department of Social Studies",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 36297,
        Location: "L9090303049",
        DepId: 5555,
        DepartmentName: "Department of Aerophysics",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 984768,
        Location: "L6448973850",
        DepId: 5556,
        DepartmentName: "Department of Science",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 501513,
        Location: "L6817740088",
        DepId: 5557,
        DepartmentName: "Department of Agriculture",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 731057,
        Location: "L1290238308",
        DepId: 5558,
        DepartmentName: "Department of Chemistry",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 413596,
        Location: "L9285153496",
        DepId: 5559,
        DepartmentName: "Department of Business",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 704459,
        Location: "L0048362115",
        DepId: 5560,
        DepartmentName: "Department of Social Studies",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 800767,
        Location: "L7681839208",
        DepId: 5555,
        DepartmentName: "Department of Aerophysics",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 51289,
        Location: "L0850481023",
        DepId: 5556,
        DepartmentName: "Department of Science",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 322330,
        Location: "L6723291123",
        DepId: 5557,
        DepartmentName: "Department of Agriculture",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 734133,
        Location: "L4371523056",
        DepId: 5558,
        DepartmentName: "Department of Chemistry",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 509034,
        Location: "L9318952570",
        DepId: 5559,
        DepartmentName: "Department of Business",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 984854,
        Location: "L6051463046",
        DepId: 5560,
        DepartmentName: "Department of Social Studies",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 359962,
        Location: "L9102217120",
        DepId: 5555,
        DepartmentName: "Department of Aerophysics",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 584452,
        Location: "L8165066552",
        DepId: 5556,
        DepartmentName: "Department of Science",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 931672,
        Location: "L4222131296",
        DepId: 5557,
        DepartmentName: "Department of Agriculture",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
    {
        BoxIdBarCode: 622621,
        Location: "L4372425023",
        DepId: 5558,
        DepartmentName: "Department of Chemistry",
        BoxDescription: "Lorem ipsum dolor sit amet, ne sed tamquam luptatum neglegentur.",
    },
]
